MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/ssy/occluded/weights/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('2')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_ETransReID'
  STRIDE_SIZE: [11, 11]
  SIE_CAMERA: True
  SIE_COE: 3.0
  JPM: True
  EFFECTIVE_RADIO: 0.5
  # decoder
  NUM_HEAD: 8
  DECODER_DROP_RATE: 0.1
  DROP_FIRST: False
  NUM_DECODER_LAYER: 1
  QUERY_NUM: 4

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.4 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('occ_duke')
  ROOT_DIR: ('/home/ssy/occluded/datasets')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  # IMS_PER_BATCH: 64
  IMS_PER_BATCH: 32
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  # LOG_PERIOD: 50
  LOG_PERIOD: 100
  # EVAL_PERIOD: 120
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.001
  COSINE_SCALE: 30
  COSINE_MARGIN: 0.5

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '/home/ssy/occluded/TransReID_occ/logs/occ_duke_vit_sie_gpart_0.5maskFilter_0.4threshold_orth_l1bseg_defg_bn_debn_operson_re0.4_pixelbag_&/transformer_best.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/occ_duke_vit_stride11_120_0.5maskFilter_0.4threshold_orth_l1bseg_defg_bn_debn_operson_re0.4_pixelbag'
# nohup python train.py --config_file /root/autodl-tmp/transreid_occ-de_occperson/configs/OCC_Duke/evit_sie_extra_part.yml  > log.file 2>&1 &
# CUDA_VISIBLE_DEVICES=1 python train.py --config_file configs/OCC_Duke/evit_sie_extra_part.yml

HUMAN_PARSING:
  IMAGE_SIZE:
  - 128
  - 384
  MODEL_FILE: '/home/ssy/occluded/weights/Human-Parsing-Network_best.pth'
  NUM_CLASSES: 10
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
        - 4
      NUM_CHANNELS:
        - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
      DOWNSAMPLE: 2
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
      DOWNSAMPLE: 2
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
      DOWNSAMPLE: 1
